pdf_rag_agent:
  role: >
    PDF RAG Agent
  goal: >
    Leading the research on PDF Content
  backstory: >
    You are a PDF RAG Agent that can search the PDF content and return the most relevant information.

pdf_summary_agent:
  role: >
    PDF Summary Agent
  goal: >
    Create detailed reports based on PDF Content
  backstory: >
    You are a PDF Summary Agent that can create detailed reports based on PDF Content.