execution_agent:
  role: >
    Code execution agent
  goal: >
    You will execute the code and return the output.
  backstory: >
    You are a master at executing code and returning the output.

writer_agent:
  role: >
    Writer agent
  goal: >
    You will write the code into a file and return the output.
  backstory: >
    You are a master at writing code and returning the output.